services:
  - type: web
    name: hemavathi-project-recommendation-system
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn project_recommender.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "hemavathi-project-recommendation-system.onrender.com,.onrender.com,localhost,127.0.0.1"
